apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tsuru.fullname" . }}-api-config
  labels:
    app: {{ template "tsuru.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  tsuru.conf: |-
    listen: "0.0.0.0:{{ .Values.service.port}}"
    host: http://{{ template "tsuru.fullname" . }}:{{ .Values.service.port}}
    repo-manager: gandalf
    git:
      api-server: http://{{ template "tsuru.fullname" . }}-gandalf:8000
    database:
      url: {{ .Release.Name }}-mongodb-replicaset:27017
      name: tsuru
    auth:
      token-expire-days: 2
      hash-cost: 4
      user-registration: true
    provisioner: kubernetes
    docker:
      bs:
        socket: /var/run/docker.sock
      cluster:
        storage: mongodb
        mongo-url: {{ .Release.Name }}-mongodb-replicaset:27017
        mongo-database: cluster
      collection: docker
      registry: {{ .Release.Name }}-docker-registry:5000
      repository-namespace: tsuru
      router: ingress-router
      deploy-cmd: /var/lib/tsuru/deploy
      run-cmd:
        bin: /var/lib/tsuru/start
        port: "8888"
      auto-scale:
        enabled: false
        run-interval: 60
    routers:
      ingress-router:
         type: api
         api-url: http://{{ .Release.Name }}-tsuru-kubernetes-router:8077/api
    queue:
      mongo-url: {{ .Release.Name }}-mongodb-replicaset:27017
      mongo-database: queuedb
    quota:
      units-per-app: 4
      apps-per-user: 2
    log:
      disable-syslog: true
      use-stderr: true
    debug: true
    #iaas: $IAAS_CONF
